// src/reactjs/detailsPresenter.jsx
import DetailsView from "../views/detailsView.jsx";
import { observer } from "mobx-react-lite";
import { useState, useEffect } from "react";
import { getDishDetails } from "/src/dishSource.js";

export default
observer(             // needed for the presenter to update (its view) when relevant parts of the model change
    function Details(props){
        const [promise, setPromise] = useState();
        const [data, setData] = useState();
        const [error, setError] = useState();

        useEffect(setPromiseACB, [props.model.currentDish]);
        useEffect(resolvePromiseACB, [promise]);

        function setPromiseACB() {
            if (props.model.currentDish != null) setPromise(getDishDetails(props.model.currentDish));
        }

        function resolvePromiseACB() {
            if (props.model.currentDish != null) {
                setData(null);
                setError(null);
                let cancelled = false;  // closure!
                promise.then(setDataACB).catch(setErrorACB);
                function setDataACB(d) {
                if (!cancelled) setData(d);
                }
                function setErrorACB(e) {
                    if (!cancelled) setError(e);
                }

                return function cancelACB() {
                    cancelled = true;
                };
            }
        }

        if (!promise) return "no data";
        if (!data && !error) return <img alt = "logo" src="https://brfenergi.se/iprog/loading.gif"/>;
        if (error) return error;
        return <DetailsView dishData={data} 
                guests={props.model.numberOfGuests} isDishInMenu={props.model.dishes.find(isDishInMenuCB)} 
                onAddToMenu={addDishToMenuACB}/>;

        function isDishInMenuCB(dish){
            console.log(dish);
            return (props.model.currentDish === dish.id);
        }

        function addDishToMenuACB() {
            props.model.addToMenu(data);
        }
    }
);

// src/vuejs/detailsPresenter.jsx
import DetailsView from "../views/detailsView.jsx";
import { getDishDetails } from "/src/dishSource.js";
import { reactive, watch } from 'vue';

export default {
    props: ['model'],
    setup(props) {
        const compState = reactive({
            promise : undefined,
            data : undefined,
            error : undefined,
        });
        // render of component state, returned below!!
        function renderACB() {
            if (!compState.promise) return "no data";
            if (!compState.data && !compState.error) return <img src="https://brfenergi.se/iprog/loading.gif"></img>;
            if (compState.error) return compState.error;
            return (<DetailsView dishData={compState.data} 
                    guests={props.model.numberOfGuests} isDishInMenu={props.model.dishes.find(isDishInMenuCB)} 
                    onAddToMenu={addDishToMenuACB}/>);
            function isDishInMenuCB(dish){
                console.log(dish);
                return (props.model.currentDish === dish.id);
            }
        
            function addDishToMenuACB() {
                props.model.addToMenu(compState.data);
            }
        }

        function resolvePromiseACB() {
            compState.data = null;
            compState.error = null;
            let cancelled = false;  // closure!
            compState.promise = getDishDetails(props.model.currentDish);
            compState.promise.then(setDataACB).catch(setErrorACB);
            function setDataACB(d) {
             if (!cancelled) compState.data = d;
            }
            function setErrorACB(e) {
              if (!cancelled) compState.error = e;
            }
        
            return function cancelACB() {
              cancelled = true;
            };
        }

        // side effect in component state 
        watch(function checkACB() {
            return [props.model.currentDish];
        }, resolvePromiseACB);

        return renderACB;
    }
}



// function Details(props){
//     if (!props.model.currentDishPromiseState.promise) return "no data";
//     if (!props.model.currentDishPromiseState.data && !props.model.currentDishPromiseState.error) return <img src="https://brfenergi.se/iprog/loading.gif"></img>;
//     if (props.model.currentDishPromiseState.error) return props.model.currentDishPromiseState.error;
//     return <DetailsView dishData={props.model.currentDishPromiseState.data} 
//             guests={props.model.numberOfGuests} isDishInMenu={props.model.dishes.find(isDishInMenuCB)} 
//             onAddToMenu={addDishToMenuACB}/>;

//     function isDishInMenuCB(dish){
//         console.log(dish);
//         return (props.model.currentDish === dish.id);
//     }

//     function addDishToMenuACB() {
//         props.model.addToMenu(props.model.currentDishPromiseState.data);
//     }
// }
